services:
  app:
    build: .
    container_name: catalog-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/catalog_db
      SPRING_DATASOURCE_USERNAME: postgres_user
      SPRING_DATASOURCE_PASSWORD: postgres_password
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

  postgres:
    image: postgres:15-alpine
    container_name: catalog-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: catalog-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # <--- Verifique esta linha com atenção

volumes:
  postgres_data:
  redis_data: